require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
    user: process.env.DB_USER,
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    password: process.env.DB_PASSWORD,
    port: process.env.DB_PORT,
});

async function createMissionTasks() {
    console.log('🚀 Creating Default Tasks for Missions...');
    const client = await pool.connect();

    try {
        await client.query('BEGIN');

        // Fetch Missions
        const res = await client.query('SELECT id, nom FROM missions');
        const missions = res.rows;
        console.log(`   Found ${missions.length} missions.`);

        let created = 0;
        let skipped = 0;

        for (const mission of missions) {
            const taskCode = `MISSION_${mission.id}`; // Logical Link
            const taskLibelle = `Mission_Task - ${mission.nom}`;

            // Check if exists
            const check = await client.query('SELECT id FROM tasks WHERE code = $1', [taskCode]);

            if (check.rows.length === 0) {
                await client.query(
                    `INSERT INTO tasks (id, code, libelle, description, created_at, updated_at, actif)
                     VALUES (gen_random_uuid(), $1, $2, 'Autogenerated task for Mission time tracking', NOW(), NOW(), true)`,
                    [taskCode, taskLibelle]
                );
                created++;
            } else {
                skipped++;
            }
        }

        await client.query('COMMIT');
        console.log(`✅ Task Creation Done.`);
        console.log(`   Created: ${created}`);
        console.log(`   Skipped: ${skipped}`);

    } catch (e) {
        await client.query('ROLLBACK');
        console.error('❌ Failed:', e);
    } finally {
        client.release();
        await pool.end();
    }
}

createMissionTasks();
